name: Build for iOS Mach-O 64

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build_ios_macho64:
    name: Build for Mach-O 64 (iOS 13.0+)
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ arm64 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.3'
          cache: true

      - name: Build for iOS Mach-O 64
        run: go build -o ipatool-ios-macho64-$GOARCH
        env:
          GOOS: ios
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 1
          CGO_CFLAGS: -mios-version-min=13.0
          CGO_LDFLAGS: -mios-version-min=13.0
          SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ipatool-ios-macho64-arm64
          path: ipatool-ios-macho64-arm64
